name: Go
on: 
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
      - /refs/heads/master

defaults:
  run:
    working-directory: ./src/github.com/SSHcom/privx-sdk-go

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  
      - name: golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/SSHcom/privx-sdk-go

      - name: Get source dependencies
        run: |
          go mod download -json

      - name: go get CI tools
        run: |
          go get github.com/mattn/goveralls
          go get github.com/lawrencewoodman/roveralls
        env:
          GO111MODULE: off

      - name: go nstall staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: go vet
        run: |
          go vet ./...
    
      - name: staticcheck
        run: |
          staticcheck ./...
  
      - name: go test
        run: |
          go test ./...
      
      - name: coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $(go env GOPATH)/src/github.com/${{ github.repository }} && roveralls
          goveralls -coverprofile=$(go env GOPATH)/src/github.com/${{ github.repository }}/roveralls.coverprofile -service=github
